apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
replicas:
  - name: fast-api-app
    count: 3
images:
  - name: 176032258835.dkr.ecr.ap-northeast-1.amazonaws.com/blue-green-ecr
    newTag: v1.0.0
patches:
  - path: deployment-patch.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: fast-api-app
  - path: ingress-patch.yaml
    target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: fast-api-app
