apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-load-balancer-controller
  namespace: argocd
spec:
  project: default
  source:
    helm:
      values: |
        serviceAccount:
          create: true
          name: aws-load-balancer-controller
        clusterName: blue