apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - path: fastapi-applications-patch.yaml
    target:
      group: argoproj.io
      version: v1alpha1
      kind: Application
      name: fastapi