apiVersion: v1
kind: Namespace
metadata:
  name: test
---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rollouts-demo
  namespace: test
spec:
  replicas: 2
  strategy:
    canary:
      canaryService: sample-preview # our created canary service
      pingPong:
        pingService: sample-ping
        pongService: sample-pong
      scaleDownDelayRevisionLimit: 1
      scaleDownDelaySeconds: 30
      steps:
        - setWeight: 0
        - setCanaryScale:
            replicas: 2
        - pause: {}
        - setWeight: 100
      trafficRouting:
        alb:
          ingresses:
            - rollouts-demo-ingress
          rootService: sample-pingpong-stable
          servicePort: 80
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: sample-app
  template:
    metadata:
      labels:
        app: sample-app
      annotations:
        linkerd.io/inject: enabled
    spec:
      containers:
        - name: sample-app
          image: 176032258835.dkr.ecr.ap-northeast-1.amazonaws.com/blue-green-ecr:20251222165149
          ports:
            - containerPort: 8080
              protocol: TCP
              name: http
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: sample-preview
  namespace: test
  labels:
    app.kubernetes.io/name: sample-app
    app.kubernetes.io/instance: sample-app
    app.kubernetes.io/version: "1.0.0"
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: sample-app
---
apiVersion: v1
kind: Service
metadata:
  name: sample-ping
  namespace: test
  labels:
    app.kubernetes.io/name: sample-app
    app.kubernetes.io/instance: sample-app
    app.kubernetes.io/version: "1.0.0"
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: sample-app
---
apiVersion: v1
kind: Service
metadata:
  name: sample-pong
  namespace: test
  labels:
    app.kubernetes.io/name: sample-app
    app.kubernetes.io/instance: sample-app
    app.kubernetes.io/version: "1.0.0"
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: sample-app
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rollouts-demo-ingress
  namespace: test
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
spec:
  rules:
    - host: test.jnytnai.click
      http:
        paths:
          - path: /test
            pathType: ImplementationSpecific
            backend:
              service:
                name: sample-preview
                port:
                  number: 80
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: sample-pingpong-stable
                port:
                  name: use-annotation
